# Generated by Django 3.0.8 on 2020-08-26 06:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problems',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='solution_progress',
            name='image_url',
        ),
        migrations.AddField(
            model_name='problems',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/', validators=[myapp.models.validate_image, django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'pdf'])]),
        ),
        migrations.AddField(
            model_name='solution_progress',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/', validators=[myapp.models.validate_image, django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'pdf'])]),
        ),
        migrations.AddField(
            model_name='solution_progress',
            name='progress',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='solution_progress',
            name='progress_details',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='problems',
            name='c_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Company'),
        ),
        migrations.AlterField(
            model_name='problems',
            name='video_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='solution_progress',
            name='video_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
